# Generated by Django 4.1.5 on 2023-01-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(choices=[('Globalnet Bronze', 'GLOBALNET_BRONZE'), ('Globalnet Silver', 'GLOBALNET_SILVER'), ('Globalnet Gold', 'GLOBALNET_GOLD')], max_length=20)),
                ('subsciptionPricePerMonthInBDT', models.FloatField()),
                ('subsciptionDurationInMonths', models.IntegerField()),
            ],
        ),
    ]
