# Generated by Django 4.1.5 on 2023-01-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_rename_subsciptiondurationinmonths_plan_subsciptionexpireinmonths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='subsciptionExpireInMonths',
            field=models.IntegerField(null=True),
        ),
    ]
