# Generated by Django 4.1.5 on 2023-01-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('phoneNumber', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('signUpDate', models.DateField()),
                ('subscriptionStartDateTime', models.DateTimeField()),
                ('totalBill', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
    ]
