# Generated by Django 4.1.5 on 2023-01-20 13:51

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='primaryPhoneNumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='ownerType',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('company', 'COMPANY')], default=customers.models.ownerTypes['PERSONAL'], max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company'),
        ),
    ]
