# Generated by Django 4.1.5 on 2023-01-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_subsciptionexpireinmonths'),
        ('customers', '0005_lastassignedphonenumbersuffix_alter_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscriptionStartDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalBill',
            field=models.FloatField(default=0),
        ),
    ]
